name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/software-installed-on-github-hosted-runners

jobs:
  windows:
    name: 'Windows (JDK 14)'
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1.1.0
      with:
        fetch-depth: 50
    - name: 'Set up JDK 14'
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: 'Test'
      shell: bash
      run: |
        ./gradlew --no-parallel build -x distTar -Duser.language=en -Duser.region=US -Duser.country=US -Dfile.encoding=UTF-8

  mac:
    name: 'macOS (JDK 14)'
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1.1.0
      with:
        fetch-depth: 50
    - name: 'Set up JDK 14'
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: 'Test'
      run: |
        ./gradlew --no-parallel build -x distTar -x distTarSource -Dskip.test_TestDNSCacheManager.testWithCustomResolverAnd1Server=true
